#!/usr/bin/env python3
"""
统一分析：从PDF到精算报告的完整流程
Unified Analysis: From PDF to Actuarial Report

整合 insurance-clause-insights 和 insurance-product-analysis，
提供从条款报告到精算分析的一站式工具。

Integrate insurance-clause-insights and insurance-product-analysis,
providing a one-stop tool from clause reports to actuarial analysis.
"""

import argparse
import json
from pathlib import Path
from typing import Optional

from actuarial_bridge import batch_analyze_from_clauses


def print_summary(results: dict) -> None:
    """打印分析结果摘要

    Print analysis result summary
    """
    print("=" * 80)
    print("精算分析完成 | Actuarial Analysis Complete")
    print("=" * 80)
    print()
    print(f"总产品数 | Total products: {results['total']}")
    print(f"成功分析 | Successfully analyzed: {results['analyzed']}")
    print(f"跳过 | Skipped: {results['skipped']}")
    print()

    if results['products']:
        print("产品排名 | Product Ranking (by IRR):")
        print("-" * 80)

        # 按 IRR 中性情景排序
        sorted_products = sorted(
            results['products'],
            key=lambda p: p['irr_neutral'],
            reverse=True
        )

        print(f"{'排名':<4} {'公司':<15} {'产品名称':<25} {'IRR中性':<10} {'评级':<6}")
        print("-" * 80)

        for i, product in enumerate(sorted_products[:10], 1):
            print(
                f"{i:<4} "
                f"{product['company']:<15} "
                f"{product['product_name']:<25} "
                f"{product['irr_neutral']:>8.2%} "
                f"{product['rating']:<6}"
            )

        print()


def export_comparison_table(results: dict, output_path: Path) -> None:
    """导出产品对比表

    Export product comparison table
    """
    if not results['products']:
        return

    # 按 IRR 排序
    sorted_products = sorted(
        results['products'],
        key=lambda p: p['irr_neutral'],
        reverse=True
    )

    table = []
    table.append("| 排名 | 公司 | 产品名称 | 类别 | 保费 | 保额 | IRR保守 | IRR中性 | IRR乐观 | 评级 |")
    table.append("|------|------|----------|------|------|------|---------|---------|---------|------|")

    for i, p in enumerate(sorted_products, 1):
        table.append(
            f"| {i} | {p['company']} | {p['product_name']} | {p['category']} | "
            f"{p['spec']['annual_premium']:,.0f} | {p['spec']['sum_assured']:,.0f} | "
            f"{p['irr_conservative']:.2%} | {p['irr_neutral']:.2%} | {p['irr_optimistic']:.2%} | "
            f"{p['rating']} |"
        )

    # 写入文件
    md_path = output_path.parent / f"{output_path.stem}_comparison.md"
    md_path.write_text("\n".join(table), encoding="utf-8")
    print(f"对比表已导出 | Comparison table exported: {md_path}")


def main():
    parser = argparse.ArgumentParser(
        description="从保险条款报告生成精算分析 | Generate actuarial analysis from insurance clause reports",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例 | Examples:
  # 基础用法 | Basic usage
  python unified_analysis.py --clause-report comparison_report.json

  # 指定默认年龄 | Specify default age
  python unified_analysis.py --clause-report comparison_report.json --default-age 40

  # 仅分析年金保险 | Analyze annuity products only
  python unified_analysis.py --clause-report comparison_report.json --category 年金保险

  # 导出对比表 | Export comparison table
  python unified_analysis.py --clause-report comparison_report.json --export-table
        """
    )

    parser.add_argument(
        "--clause-report",
        type=Path,
        required=True,
        help="insurance-clause-insights 生成的 comparison_report.json 路径 | Path to comparison_report.json generated by insurance-clause-insights"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("outputs/unified_analysis.json"),
        help="输出文件路径 | Output file path (default: outputs/unified_analysis.json)"
    )
    parser.add_argument(
        "--default-age",
        type=int,
        default=30,
        help="缺失年龄时的默认值 | Default age when missing (default: 30)"
    )
    parser.add_argument(
        "--default-gender",
        type=str,
        default="M",
        choices=["M", "F"],
        help="缺失性别时的默认值 | Default gender when missing (default: M)"
    )
    parser.add_argument(
        "--min-completeness",
        type=float,
        default=0.6,
        help="最小参数完整性阈值 | Minimum parameter completeness threshold (default: 0.6)"
    )
    parser.add_argument(
        "--category",
        type=str,
        help="仅分析指定类别 | Only analyze specified category"
    )
    parser.add_argument(
        "--export-table",
        action="store_true",
        help="导出Markdown格式的对比表 | Export comparison table in Markdown format"
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="静默模式，仅输出结果文件 | Quiet mode, only output result file"
    )

    args = parser.parse_args()

    # 执行批量分析
    results = batch_analyze_from_clauses(
        clause_report_path=args.clause_report,
        default_age=args.default_age,
        default_gender=args.default_gender,
        min_completeness=args.min_completeness,
    )

    # 过滤类别
    if args.category:
        original_count = len(results["products"])
        results["products"] = [
            p for p in results["products"]
            if args.category in p["category"]
        ]
        results["analyzed"] = len(results["products"])
        results["skipped"] += original_count - results["analyzed"]

    # 输出结果
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(results, ensure_ascii=False, indent=2),
        encoding="utf-8"
    )

    if not args.quiet:
        print_summary(results)

        # 导出对比表
        if args.export_table:
            export_comparison_table(results, args.output)

        print(f"✅ 分析完成 | Analysis complete!")
        print(f"📄 结果文件 | Result file: {args.output}")
        print()
        print("💡 提示 | Tips:")
        print("  - 查看完整结果: cat outputs/unified_analysis.json | jq")
        print("  - 仅查看产品列表: cat outputs/unified_analysis.json | jq '.products[] | {product_name, irr_neutral, rating}'")


if __name__ == "__main__":
    main()
